const subjects = [
  {
    id: "biology", icon: "🧬", name: "Biology", color: "green", description: "Explore living systems from cells and genetics to ecosystems and evolution.", level: "High school", topics: [
      { id:"cell-structure", name:"Cell Structure", time:"12 min", difficulty:"Foundation", overview:"Cells are the smallest units capable of carrying out all processes of life. Understanding their structures explains how organisms obtain energy, build materials, communicate, and reproduce.", points:["Prokaryotic cells lack a membrane-bound nucleus; eukaryotic cells contain one.","The cell membrane controls movement using selective permeability.","Mitochondria release usable energy through cellular respiration.","Ribosomes assemble proteins from amino acids.","Plant cells also contain chloroplasts, a large central vacuole, and a cell wall."], terms:[["Organelle","A specialized structure that performs a particular job inside a cell."],["Cytoplasm","The fluid and structures between the membrane and nucleus."],["Homeostasis","Maintaining stable internal conditions."],["Diffusion","Net movement from higher to lower concentration."]], check:["Compare prokaryotes and eukaryotes","Match organelles to their functions","Explain membrane transport"] },
      { id:"photosynthesis", name:"Photosynthesis", time:"10 min", difficulty:"Foundation", overview:"Photosynthesis captures light energy and stores it as chemical energy in glucose. It supports nearly every food web and helps regulate atmospheric carbon dioxide and oxygen.", points:["The overall reaction uses carbon dioxide and water to produce glucose and oxygen.","Light-dependent reactions occur in thylakoid membranes.","The Calvin cycle builds sugars in the chloroplast stroma.","Chlorophyll absorbs mostly red and blue wavelengths.","Light, carbon dioxide, and temperature can limit the reaction rate."], terms:[["Chlorophyll","The primary light-absorbing pigment in plants."],["Thylakoid","A chloroplast membrane where light reactions occur."],["Stroma","Fluid surrounding thylakoids where the Calvin cycle occurs."],["Glucose","A sugar that stores chemical energy."]], check:["Write the balanced overall equation","Connect chloroplast structures to stages","Predict effects of limiting factors"] },
      { id:"genetics", name:"Genetics & Heredity", time:"18 min", difficulty:"Intermediate", overview:"Genetics explains how biological information is stored, expressed, and passed between generations. Patterns of inheritance connect DNA to observable traits.", points:["Genes are DNA sequences that influence functional products.","Alleles are alternative versions of a gene.","Meiosis creates genetically varied haploid gametes.","Dominant alleles are expressed in heterozygotes; recessive ones require two copies.","Most traits reflect multiple genes and environmental effects."], terms:[["Genotype","An organism’s allele combination."],["Phenotype","An observable characteristic."],["Homozygous","Having two identical alleles."],["Heterozygous","Having two different alleles."]], check:["Complete monohybrid Punnett squares","Distinguish genotype from phenotype","Explain how meiosis creates variation"] },
      { id:"evolution", name:"Evolution", time:"16 min", difficulty:"Intermediate", overview:"Evolution is change in inherited characteristics of populations over generations. Natural selection is one mechanism, acting when heritable variation affects reproductive success.", points:["Individuals vary, but populations evolve.","Natural selection requires heritable variation and unequal reproductive success.","Mutations and recombination generate genetic variation.","Evidence includes fossils, homologous structures, biogeography, and DNA.","Selection adapts populations to current environments; it does not pursue a goal."], terms:[["Natural selection","Differential survival and reproduction based on inherited traits."],["Adaptation","A heritable trait that increases fitness in an environment."],["Fitness","Relative reproductive success."],["Common ancestor","An ancestral population shared by descendant groups."]], check:["State the conditions for natural selection","Interpret a simple phylogenetic tree","Correct goal-directed misconceptions"] }
    ]
  },
  {
    id: "algebra", icon: "📐", name: "Algebra", color: "blue", description: "Build confidence with equations, functions, graphs, and mathematical reasoning.", level: "Algebra I–II", topics: [
      { id:"linear-equations", name:"Linear Equations", time:"12 min", difficulty:"Foundation", overview:"Linear equations describe relationships with a constant rate of change. Solving them means isolating the variable while preserving equality.", points:["Apply the same operation to both sides of an equation.","Combine like terms before isolating the variable.","Distribute multiplication across every term inside parentheses.","A contradiction means no solution; an identity means infinitely many.","Check solutions by substituting them into the original equation."], terms:[["Coefficient","A number multiplying a variable."],["Constant","A term with no variable."],["Like terms","Terms containing identical variable factors."],["Inverse operation","An operation that reverses another operation."]], check:["Solve multi-step equations","Handle variables on both sides","Identify special solution cases"] },
      { id:"slope", name:"Slope & Graphing", time:"14 min", difficulty:"Foundation", overview:"Slope measures the rate at which one variable changes relative to another. In a coordinate plane, it describes a line’s direction and steepness.", points:["Slope equals rise divided by run: change in y over change in x.","Slope-intercept form is y = mx + b.","Parallel lines share a slope.","Perpendicular nonvertical lines have negative reciprocal slopes.","A vertical line has undefined slope; a horizontal line has zero slope."], terms:[["Slope","Rate of change between two variables."],["Y-intercept","Where a graph crosses the y-axis."],["Rate of change","Output change divided by input change."],["Linear function","A function with constant rate of change."]], check:["Calculate slope from two points","Graph from slope-intercept form","Write an equation from a graph"] },
      { id:"systems", name:"Systems of Equations", time:"16 min", difficulty:"Intermediate", overview:"A system asks for values that satisfy multiple equations simultaneously. Graphing, substitution, and elimination reveal where the relationships agree.", points:["A solution is an ordered pair satisfying every equation.","Graphing finds intersection points visually.","Substitution replaces a variable with an equivalent expression.","Elimination combines equations to cancel one variable.","Systems can have one, zero, or infinitely many solutions."], terms:[["System","Two or more equations considered together."],["Substitution","Replacing an expression with an equal expression."],["Elimination","Adding equations to cancel a variable."],["Intersection","A point shared by graphs."]], check:["Choose an efficient solution method","Solve and verify a two-variable system","Interpret solutions in context"] },
      { id:"quadratics", name:"Quadratic Functions", time:"20 min", difficulty:"Intermediate", overview:"Quadratic functions model relationships with a squared variable. Their parabolic graphs connect factors, roots, vertices, and rates of change.", points:["Standard form is ax² + bx + c with a not equal to zero.","Zeros are x-values where the graph crosses or touches the x-axis.","The vertex is the maximum or minimum point.","Factoring, completing the square, and the quadratic formula solve equations.","The discriminant predicts the number of real solutions."], terms:[["Parabola","The U-shaped graph of a quadratic function."],["Vertex","The turning point of a parabola."],["Zero","An input producing an output of zero."],["Discriminant","The expression b² − 4ac."]], check:["Move between quadratic forms","Find zeros and the vertex","Use the quadratic formula accurately"] }
    ]
  },
  {
    id: "world-history", icon: "🌍", name: "World History", color: "gold", description: "Connect major civilizations, turning points, ideas, and global transformations.", level: "High school", topics: [
      { id:"ancient-civilizations", name:"Ancient Civilizations", time:"18 min", difficulty:"Foundation", overview:"Early civilizations developed around productive environments and built institutions to manage food, labor, belief, conflict, and trade.", points:["River valleys supported intensive agriculture and larger populations.","Writing enabled recordkeeping, law, administration, and literature.","Social hierarchies organized labor and political authority.","Religious traditions helped explain nature and legitimize rulers.","Trade spread technologies, materials, languages, and ideas."], terms:[["Civilization","A complex society with cities, institutions, and specialized labor."],["City-state","An independent city and its surrounding territory."],["Cuneiform","A wedge-shaped Mesopotamian writing system."],["Mandate of Heaven","A Chinese principle linking rule to moral legitimacy."]], check:["Compare two river-valley societies","Explain why writing changed government","Connect geography to development"] },
      { id:"silk-roads", name:"Silk Roads & Exchange", time:"14 min", difficulty:"Intermediate", overview:"Long-distance exchange networks connected Afro-Eurasian societies. Merchants moved luxury goods, while travelers also carried religions, technologies, crops, and diseases.", points:["The Silk Roads were a network rather than one continuous road.","Caravan cities and states profited by protecting and taxing trade.","Buddhism, Islam, and other beliefs spread along trade routes.","Paper-making and other technologies traveled between regions.","Disease transmission demonstrated the biological costs of connectivity."], terms:[["Caravanserai","A roadside inn supporting merchants and animals."],["Cultural diffusion","Spread of ideas and customs between societies."],["Diaspora","A dispersed community maintaining connections to a homeland."],["Pax Mongolica","Relative stability across Mongol-controlled Eurasia."]], check:["Identify goods and ideas exchanged","Explain the role of states","Evaluate benefits and costs of connection"] },
      { id:"industrial-revolution", name:"Industrial Revolution", time:"20 min", difficulty:"Intermediate", overview:"Industrialization shifted production from hand labor toward machines and factories, transforming economies, cities, social classes, environments, and global power.", points:["Britain combined capital, coal, labor, markets, and political conditions favorable to industry.","Factories concentrated workers and machinery in one location.","Urbanization grew rapidly and often outpaced sanitation and housing.","Industrial capitalism expanded middle and working classes.","Labor movements and reform laws responded to dangerous conditions."], terms:[["Industrialization","Growth of machine-based factory production."],["Urbanization","Increasing concentration of people in cities."],["Capital","Resources invested to create more wealth."],["Proletariat","Industrial wage-working class."]], check:["Explain why Britain industrialized first","Compare social benefits and costs","Connect industry to imperialism"] },
      { id:"world-war-i", name:"World War I", time:"22 min", difficulty:"Intermediate", overview:"World War I grew from long-term tensions and a regional crisis into industrialized global warfare. Its destruction reshaped borders, governments, societies, and later conflicts.", points:["Militarism, alliances, imperial competition, and nationalism increased tension.","The assassination of Archduke Franz Ferdinand triggered the July Crisis.","Trench warfare and modern weapons created stalemate and mass casualties.","Total war mobilized economies and civilian populations.","The peace settlement redrew borders but left major grievances unresolved."], terms:[["Militarism","Glorification and expansion of military power."],["Total war","Mobilization of an entire society for conflict."],["Armistice","An agreement to stop fighting."],["Self-determination","The idea that peoples should choose their political status."]], check:["Separate long-term causes from the trigger","Explain the Western Front stalemate","Evaluate consequences of the peace settlement"] }
    ]
  }
];

export function SubjectLibrary({ pathname, onPath, onTool }) {
  const parts = pathname.split("/").filter(Boolean);
  const subject = subjects.find((item) => item.id === parts[1]);
  const topic = subject?.topics.find((item) => item.id === parts[2]);
  if (topic) return <TopicPage subject={subject} topic={topic} onPath={onPath} onTool={onTool}/>;
  if (subject) return <SubjectPage subject={subject} onPath={onPath}/>;
  return <Catalog onPath={onPath}/>;
}

function Catalog({ onPath }) {
  return <main className="subject-page"><section className="subject-hero"><span className="eyebrow">SHIBAAI SUBJECT LIBRARY</span><h1>Ready-made guides.<br/>Real understanding.</h1><p>Browse focused, student-friendly guides and turn any topic into active practice with one click.</p><div className="catalog-stats"><span><b>3</b> launch subjects</span><span><b>12</b> complete guides</span><span><b>100%</b> free preview</span></div></section><section className="subject-catalog"><div className="catalog-heading"><div><span className="eyebrow">CHOOSE A SUBJECT</span><h2>Where do you want to start?</h2></div><p>Every guide includes concepts, vocabulary, a review checklist, and AI-powered practice options.</p></div><div className="subject-grid">{subjects.map((subject) => <button className={`subject-card ${subject.color}`} key={subject.id} onClick={() => onPath(`/subjects/${subject.id}`)}><span className="subject-icon">{subject.icon}</span><div><small>{subject.level} · {subject.topics.length} guides</small><h2>{subject.name}</h2><p>{subject.description}</p><b>Explore {subject.name} →</b></div></button>)}</div><div className="coming-subjects"><span>COMING NEXT</span><div>🧪 Chemistry　⚛️ Physics　📚 Literature　🧠 Psychology　💻 Computer Science</div></div></section></main>;
}

function SubjectPage({ subject, onPath }) {
  return <main className="subject-page"><section className={`subject-detail-hero ${subject.color}`}><button onClick={() => onPath("/subjects")}>← All subjects</button><span>{subject.icon}</span><small>{subject.level}</small><h1>{subject.name}</h1><p>{subject.description}</p></section><section className="topic-section"><div className="catalog-heading"><div><span className="eyebrow">STUDY GUIDES</span><h2>Start with a core topic.</h2></div><p>Read the guide first, then use active practice to check what you remember.</p></div><div className="topic-grid">{subject.topics.map((topic,index) => <button key={topic.id} onClick={() => onPath(`/subjects/${subject.id}/${topic.id}`)}><span>{String(index+1).padStart(2,"0")}</span><div><small>{topic.difficulty} · {topic.time}</small><h3>{topic.name}</h3><p>{topic.overview}</p></div><b>→</b></button>)}</div></section></main>;
}

function TopicPage({ subject, topic, onPath, onTool }) {
  return <main className="guide-page"><nav className="guide-breadcrumb"><button onClick={() => onPath("/subjects")}>Subjects</button><span>/</span><button onClick={() => onPath(`/subjects/${subject.id}`)}>{subject.name}</button><span>/</span><b>{topic.name}</b></nav><header className={`guide-header ${subject.color}`}><div><span className="eyebrow">{subject.name.toUpperCase()} STUDY GUIDE</span><h1>{topic.name}</h1><p>{topic.overview}</p><div className="guide-meta"><span>◷ {topic.time}</span><span>◈ {topic.difficulty}</span><span>✓ Review checklist</span></div></div><span className="guide-mascot">{subject.icon}</span></header><div className="guide-layout"><article className="guide-content"><section><span className="section-number">01</span><div><h2>Key concepts</h2><ul className="concept-list">{topic.points.map((point) => <li key={point}><span>✓</span>{point}</li>)}</ul></div></section><section><span className="section-number">02</span><div><h2>Essential vocabulary</h2><div className="vocab-list">{topic.terms.map(([term,definition]) => <div key={term}><strong>{term}</strong><p>{definition}</p></div>)}</div></div></section><section><span className="section-number">03</span><div><h2>Before you move on</h2><p className="check-intro">You’re ready when you can complete these without looking back:</p><div className="review-checks">{topic.check.map((item) => <label key={item}><input type="checkbox"/><span>{item}</span></label>)}</div></div></section></article><aside className="guide-sidebar"><div className="guide-action-card"><span>🐕</span><h3>Practice with Shiba</h3><p>Use this topic as a starting point for personalized study materials.</p><button className="button" onClick={() => onTool("quiz",topic)}>Generate a quiz</button><button onClick={() => onTool("flashcards",topic)}>Make flashcards</button></div><div className="guide-note"><strong>Remember</strong><p>AI-generated practice may make mistakes. Compare answers with this guide and your class materials.</p></div></aside></div></main>;
}

export { subjects };
