const subjects = [
  {
    id: "biology", icon: "🧬", name: "Biology", color: "green", description: "Explore living systems from cells and genetics to ecosystems and evolution.", level: "High school", topics: [
      { id:"cell-structure", name:"Cell Structure", time:"12 min", difficulty:"Foundation", overview:"Cells are the smallest units capable of carrying out all processes of life. Understanding their structures explains how organisms obtain energy, build materials, communicate, and reproduce.", points:["Prokaryotic cells lack a membrane-bound nucleus; eukaryotic cells contain one.","The cell membrane controls movement using selective permeability.","Mitochondria release usable energy through cellular respiration.","Ribosomes assemble proteins from amino acids.","Plant cells also contain chloroplasts, a large central vacuole, and a cell wall."], terms:[["Organelle","A specialized structure that performs a particular job inside a cell."],["Cytoplasm","The fluid and structures between the membrane and nucleus."],["Homeostasis","Maintaining stable internal conditions."],["Diffusion","Net movement from higher to lower concentration."]], check:["Compare prokaryotes and eukaryotes","Match organelles to their functions","Explain membrane transport"] },
      { id:"photosynthesis", name:"Photosynthesis", time:"10 min", difficulty:"Foundation", overview:"Photosynthesis captures light energy and stores it as chemical energy in glucose. It supports nearly every food web and helps regulate atmospheric carbon dioxide and oxygen.", points:["The overall reaction uses carbon dioxide and water to produce glucose and oxygen.","Light-dependent reactions occur in thylakoid membranes.","The Calvin cycle builds sugars in the chloroplast stroma.","Chlorophyll absorbs mostly red and blue wavelengths.","Light, carbon dioxide, and temperature can limit the reaction rate."], terms:[["Chlorophyll","The primary light-absorbing pigment in plants."],["Thylakoid","A chloroplast membrane where light reactions occur."],["Stroma","Fluid surrounding thylakoids where the Calvin cycle occurs."],["Glucose","A sugar that stores chemical energy."]], check:["Write the balanced overall equation","Connect chloroplast structures to stages","Predict effects of limiting factors"] },
      { id:"genetics", name:"Genetics & Heredity", time:"18 min", difficulty:"Intermediate", overview:"Genetics explains how biological information is stored, expressed, and passed between generations. Patterns of inheritance connect DNA to observable traits.", points:["Genes are DNA sequences that influence functional products.","Alleles are alternative versions of a gene.","Meiosis creates genetically varied haploid gametes.","Dominant alleles are expressed in heterozygotes; recessive ones require two copies.","Most traits reflect multiple genes and environmental effects."], terms:[["Genotype","An organism’s allele combination."],["Phenotype","An observable characteristic."],["Homozygous","Having two identical alleles."],["Heterozygous","Having two different alleles."]], check:["Complete monohybrid Punnett squares","Distinguish genotype from phenotype","Explain how meiosis creates variation"] },
      { id:"evolution", name:"Evolution", time:"16 min", difficulty:"Intermediate", overview:"Evolution is change in inherited characteristics of populations over generations. Natural selection is one mechanism, acting when heritable variation affects reproductive success.", points:["Individuals vary, but populations evolve.","Natural selection requires heritable variation and unequal reproductive success.","Mutations and recombination generate genetic variation.","Evidence includes fossils, homologous structures, biogeography, and DNA.","Selection adapts populations to current environments; it does not pursue a goal."], terms:[["Natural selection","Differential survival and reproduction based on inherited traits."],["Adaptation","A heritable trait that increases fitness in an environment."],["Fitness","Relative reproductive success."],["Common ancestor","An ancestral population shared by descendant groups."]], check:["State the conditions for natural selection","Interpret a simple phylogenetic tree","Correct goal-directed misconceptions"] }
    ]
  },
  {
    id: "algebra", icon: "📐", name: "Algebra", color: "blue", description: "Build confidence with equations, functions, graphs, and mathematical reasoning.", level: "Algebra I–II", topics: [
      { id:"linear-equations", name:"Linear Equations", time:"12 min", difficulty:"Foundation", overview:"Linear equations describe relationships with a constant rate of change. Solving them means isolating the variable while preserving equality.", points:["Apply the same operation to both sides of an equation.","Combine like terms before isolating the variable.","Distribute multiplication across every term inside parentheses.","A contradiction means no solution; an identity means infinitely many.","Check solutions by substituting them into the original equation."], terms:[["Coefficient","A number multiplying a variable."],["Constant","A term with no variable."],["Like terms","Terms containing identical variable factors."],["Inverse operation","An operation that reverses another operation."]], check:["Solve multi-step equations","Handle variables on both sides","Identify special solution cases"] },
      { id:"slope", name:"Slope & Graphing", time:"14 min", difficulty:"Foundation", overview:"Slope measures the rate at which one variable changes relative to another. In a coordinate plane, it describes a line’s direction and steepness.", points:["Slope equals rise divided by run: change in y over change in x.","Slope-intercept form is y = mx + b.","Parallel lines share a slope.","Perpendicular nonvertical lines have negative reciprocal slopes.","A vertical line has undefined slope; a horizontal line has zero slope."], terms:[["Slope","Rate of change between two variables."],["Y-intercept","Where a graph crosses the y-axis."],["Rate of change","Output change divided by input change."],["Linear function","A function with constant rate of change."]], check:["Calculate slope from two points","Graph from slope-intercept form","Write an equation from a graph"] },
      { id:"systems", name:"Systems of Equations", time:"16 min", difficulty:"Intermediate", overview:"A system asks for values that satisfy multiple equations simultaneously. Graphing, substitution, and elimination reveal where the relationships agree.", points:["A solution is an ordered pair satisfying every equation.","Graphing finds intersection points visually.","Substitution replaces a variable with an equivalent expression.","Elimination combines equations to cancel one variable.","Systems can have one, zero, or infinitely many solutions."], terms:[["System","Two or more equations considered together."],["Substitution","Replacing an expression with an equal expression."],["Elimination","Adding equations to cancel a variable."],["Intersection","A point shared by graphs."]], check:["Choose an efficient solution method","Solve and verify a two-variable system","Interpret solutions in context"] },
      { id:"quadratics", name:"Quadratic Functions", time:"20 min", difficulty:"Intermediate", overview:"Quadratic functions model relationships with a squared variable. Their parabolic graphs connect factors, roots, vertices, and rates of change.", points:["Standard form is ax² + bx + c with a not equal to zero.","Zeros are x-values where the graph crosses or touches the x-axis.","The vertex is the maximum or minimum point.","Factoring, completing the square, and the quadratic formula solve equations.","The discriminant predicts the number of real solutions."], terms:[["Parabola","The U-shaped graph of a quadratic function."],["Vertex","The turning point of a parabola."],["Zero","An input producing an output of zero."],["Discriminant","The expression b² − 4ac."]], check:["Move between quadratic forms","Find zeros and the vertex","Use the quadratic formula accurately"] }
    ]
  },
  {
    id: "world-history", icon: "🌍", name: "World History", color: "gold", description: "Connect major civilizations, turning points, ideas, and global transformations.", level: "High school", topics: [
      { id:"ancient-civilizations", name:"Ancient Civilizations", time:"18 min", difficulty:"Foundation", overview:"Early civilizations developed around productive environments and built institutions to manage food, labor, belief, conflict, and trade.", points:["River valleys supported intensive agriculture and larger populations.","Writing enabled recordkeeping, law, administration, and literature.","Social hierarchies organized labor and political authority.","Religious traditions helped explain nature and legitimize rulers.","Trade spread technologies, materials, languages, and ideas."], terms:[["Civilization","A complex society with cities, institutions, and specialized labor."],["City-state","An independent city and its surrounding territory."],["Cuneiform","A wedge-shaped Mesopotamian writing system."],["Mandate of Heaven","A Chinese principle linking rule to moral legitimacy."]], check:["Compare two river-valley societies","Explain why writing changed government","Connect geography to development"] },
      { id:"silk-roads", name:"Silk Roads & Exchange", time:"14 min", difficulty:"Intermediate", overview:"Long-distance exchange networks connected Afro-Eurasian societies. Merchants moved luxury goods, while travelers also carried religions, technologies, crops, and diseases.", points:["The Silk Roads were a network rather than one continuous road.","Caravan cities and states profited by protecting and taxing trade.","Buddhism, Islam, and other beliefs spread along trade routes.","Paper-making and other technologies traveled between regions.","Disease transmission demonstrated the biological costs of connectivity."], terms:[["Caravanserai","A roadside inn supporting merchants and animals."],["Cultural diffusion","Spread of ideas and customs between societies."],["Diaspora","A dispersed community maintaining connections to a homeland."],["Pax Mongolica","Relative stability across Mongol-controlled Eurasia."]], check:["Identify goods and ideas exchanged","Explain the role of states","Evaluate benefits and costs of connection"] },
      { id:"industrial-revolution", name:"Industrial Revolution", time:"20 min", difficulty:"Intermediate", overview:"Industrialization shifted production from hand labor toward machines and factories, transforming economies, cities, social classes, environments, and global power.", points:["Britain combined capital, coal, labor, markets, and political conditions favorable to industry.","Factories concentrated workers and machinery in one location.","Urbanization grew rapidly and often outpaced sanitation and housing.","Industrial capitalism expanded middle and working classes.","Labor movements and reform laws responded to dangerous conditions."], terms:[["Industrialization","Growth of machine-based factory production."],["Urbanization","Increasing concentration of people in cities."],["Capital","Resources invested to create more wealth."],["Proletariat","Industrial wage-working class."]], check:["Explain why Britain industrialized first","Compare social benefits and costs","Connect industry to imperialism"] },
      { id:"world-war-i", name:"World War I", time:"22 min", difficulty:"Intermediate", overview:"World War I grew from long-term tensions and a regional crisis into industrialized global warfare. Its destruction reshaped borders, governments, societies, and later conflicts.", points:["Militarism, alliances, imperial competition, and nationalism increased tension.","The assassination of Archduke Franz Ferdinand triggered the July Crisis.","Trench warfare and modern weapons created stalemate and mass casualties.","Total war mobilized economies and civilian populations.","The peace settlement redrew borders but left major grievances unresolved."], terms:[["Militarism","Glorification and expansion of military power."],["Total war","Mobilization of an entire society for conflict."],["Armistice","An agreement to stop fighting."],["Self-determination","The idea that peoples should choose their political status."]], check:["Separate long-term causes from the trigger","Explain the Western Front stalemate","Evaluate consequences of the peace settlement"] }
    ]
  },
  {
    id:"chemistry", icon:"🧪", name:"Chemistry", color:"blue", description:"Understand matter, reactions, bonding, energy, and the quantitative patterns behind chemical change.", level:"High school", topics:[
      { id:"atomic-structure", name:"Atomic Structure & Periodicity", time:"24 min", difficulty:"Foundation", overview:"Atomic structure connects subatomic particles, electron arrangements, and periodic trends. These ideas explain why elements form particular ions, bonds, and compounds.", points:["Atomic number equals the number of protons and identifies an element.","Isotopes share a proton number but differ in neutrons and mass.","Electrons occupy quantized energy levels and orbitals.","Valence electrons largely determine bonding and reactivity.","Effective nuclear charge and shielding explain major periodic trends.","Atomic radius generally decreases across a period and increases down a group."], detail:["An atom contains a dense nucleus of protons and neutrons surrounded by electrons. Protons determine identity, while changing the number of neutrons creates isotopes. A neutral atom has equal numbers of protons and electrons; ions form when electrons are gained or lost.","Electron configurations describe how electrons fill orbitals. The outermost electrons are especially important because chemical reactions rearrange valence electrons rather than atomic nuclei.","Periodic trends are connected, not separate facts to memorize. Across a period, increasing nuclear charge pulls electrons closer. Down a group, added energy levels increase distance and shielding, making atoms larger."], terms:[["Atomic number","The number of protons in an atom's nucleus."],["Isotope","Atoms of one element with different neutron counts."],["Orbital","A region where an electron is likely to be found."],["Valence electron","An electron in the highest occupied energy level."],["Ionization energy","Energy required to remove an electron from a gaseous atom."]], check:["Determine protons, neutrons, and electrons from isotope notation","Write basic electron configurations","Explain atomic-radius and ionization-energy trends","Predict common ion charges from group position"] },
      { id:"chemical-bonding", name:"Chemical Bonding & Molecular Shape", time:"26 min", difficulty:"Intermediate", overview:"Chemical bonds form because interacting atoms can reach lower-energy arrangements. Bond type, polarity, and molecular geometry determine many physical and chemical properties.", points:["Ionic bonding involves electrostatic attraction between oppositely charged ions.","Covalent bonds share electron pairs between atoms.","Electronegativity differences help predict bond polarity.","Lewis structures track valence electrons and bonding pairs.","VSEPR theory predicts shape by minimizing electron-domain repulsion.","Molecular polarity depends on both bond polarity and three-dimensional symmetry."], detail:["Metals commonly lose electrons and nonmetals gain them, producing ionic lattices rather than isolated molecule pairs. Covalent substances form when atoms share electrons; the sharing may be equal or unequal.","A Lewis structure is a bookkeeping model. Count total valence electrons, connect atoms, complete outer shells, and then check formal charges. Resonance is used when more than one valid electron arrangement contributes to the real structure.","Shape matters because bond dipoles are vectors. Carbon dioxide has polar bonds but is nonpolar overall because its linear dipoles cancel; water remains polar because its bent geometry prevents cancellation."], terms:[["Electronegativity","An atom's attraction for shared electrons."],["Lewis structure","A diagram of valence electrons and bonds."],["Resonance","Multiple valid structures representing electron delocalization."],["VSEPR","A model predicting geometry from electron-pair repulsion."],["Dipole","A separation of partial positive and negative charge."]], check:["Classify ionic, polar covalent, and nonpolar covalent bonds","Draw Lewis structures with correct electron counts","Predict common molecular geometries","Determine whether a whole molecule is polar"] },
      { id:"stoichiometry", name:"Reactions & Stoichiometry", time:"30 min", difficulty:"Intermediate", overview:"Stoichiometry uses balanced equations and the mole to measure chemical change. It links microscopic particle ratios to masses and quantities measured in a laboratory.", points:["Balanced equations conserve each type of atom.","Coefficients represent particle and mole ratios, not mass ratios.","One mole contains Avogadro's number of representative particles.","Molar mass converts between grams and moles.","The limiting reactant determines the maximum possible product.","Percent yield compares actual experimental output with theoretical yield."], detail:["Begin every calculation with a balanced equation. Subscripts describe a substance and may not be changed during balancing; coefficients scale entire formulas until atom counts match on both sides.","A reliable stoichiometry path is given unit → moles of given → moles of wanted → wanted unit. The balanced equation supplies only the middle mole ratio, while molar mass or particle conversions handle the ends.","When two reactants are given, calculate product from each independently. The smaller predicted amount identifies the limiting reactant. Real yields are often lower because reactions may be incomplete or material can be lost during transfer and purification."], terms:[["Mole","Exactly 6.02214076 × 10²³ entities."],["Molar mass","Mass in grams of one mole of a substance."],["Coefficient","A whole-number reaction multiplier."],["Limiting reactant","The reactant consumed first."],["Theoretical yield","Maximum product predicted by stoichiometry."]], check:["Balance equations without changing formulas","Convert among particles, moles, and grams","Solve a multi-step mole-ratio problem","Identify limiting reactant and calculate percent yield"] }
    ]
  },
  {
    id:"literature", icon:"📚", name:"Literature", color:"gold", description:"Read closely, analyze craft, build interpretations, and support arguments with precise textual evidence.", level:"Grades 9–12", topics:[
      { id:"close-reading", name:"Close Reading & Annotation", time:"22 min", difficulty:"Foundation", overview:"Close reading examines how specific language choices create meaning. Strong readers move from observation to pattern, interpretation, and evidence-based explanation.", points:["Annotate selectively for patterns rather than highlighting everything.","Distinguish literal events from implications and connotations.","Track repetition, contrast, shifts, and unresolved tensions.","Ask how diction and syntax shape tone and pace.","Develop interpretations that explain multiple details at once.","Use context without replacing analysis of the text itself."], detail:["Start by establishing the literal situation: who speaks, what happens, and what changes. Then notice details that seem emphasized, surprising, repeated, or inconsistent.","Patterns turn observations into analysis. Repeated images of doors, borders, or thresholds, for example, may develop an idea about belonging or transition. The goal is not to name a device but to explain its effect.","A defensible interpretation remains open to complexity. Instead of claiming that a symbol has one universal meaning, explain what it suggests in this particular passage and how surrounding language supports that reading."], terms:[["Diction","An author's deliberate word choice."],["Syntax","The arrangement of words and clauses."],["Connotation","Emotional or cultural associations of a word."],["Motif","A recurring element that develops an idea."],["Ambiguity","Language that supports more than one interpretation."]], check:["Summarize a passage literally before interpreting it","Identify a meaningful textual pattern","Explain how a quoted detail produces an effect","Write an interpretation that acknowledges complexity"] },
      { id:"character-theme", name:"Character, Conflict & Theme", time:"26 min", difficulty:"Intermediate", overview:"Characters reveal values through choices under pressure. Following motivation, conflict, and change helps readers develop themes as claims about human experience rather than one-word topics.", points:["Characterization can be direct or inferred from action, dialogue, and response.","Internal and external conflicts often interact.","A foil highlights traits through contrast.","Character arcs may involve growth, decline, revelation, or refusal to change.","Theme is a developed claim, not a single abstract noun.","Plot outcomes can complicate rather than simply prove a theme."], detail:["Track what a character wants, what prevents it, and what the character is willing to sacrifice. Contradictions between stated beliefs and actual choices often reveal the most important tensions.","Move from topic to theme by completing a sentence. Instead of writing 'the theme is power,' argue that 'power maintained through fear eventually isolates the person who holds it.' Then test the claim against the beginning, turning point, and ending.","Complex works may present competing thematic possibilities through different characters. A strong analysis explains how the text weighs those positions instead of forcing every event into one simple moral."], terms:[["Characterization","Methods used to construct a character."],["Foil","A character whose contrast highlights another."],["Internal conflict","A struggle within a character."],["Theme","A work's developed idea about life or society."],["Character arc","A pattern of change across a narrative."]], check:["Infer motivation from specific behavior","Connect internal and external conflict","Turn a topic into a complete thematic claim","Use events from multiple parts of a text as support"] },
      { id:"literary-argument", name:"Writing a Literary Analysis", time:"32 min", difficulty:"Intermediate", overview:"Literary analysis makes a debatable claim about how a text creates meaning and supports it through carefully selected evidence, reasoning, and attention to authorial choices.", points:["A thesis should be specific, debatable, and answer how or why.","Topic sentences state analytical reasons rather than plot events.","Evidence must be introduced, quoted accurately, and interpreted.","Commentary should explain language and connect it to the claim.","Counterevidence can strengthen a nuanced argument.","Revision should improve reasoning and organization before sentence polish."], detail:["Build a thesis from a pattern you can demonstrate. A useful structure names the authorial choice, its effect, and the larger significance without turning into a three-part checklist.","Use quotations as evidence, not as replacements for explanation. After quoting, focus on the most important words, images, syntax, or contrast and show the reader exactly how those details support the paragraph's reason.","During revision, reverse-outline each paragraph in a few words. If two paragraphs do the same job, combine or distinguish them. If a paragraph does not advance the thesis, revise its purpose or remove it."], terms:[["Thesis","The central arguable claim of an essay."],["Commentary","Reasoning that connects evidence to a claim."],["Context","Information needed to understand evidence."],["Counterargument","A credible alternative interpretation."],["Synthesis","Combining evidence into a broader conclusion."]], check:["Write a debatable how-or-why thesis","Build a paragraph around one analytical reason","Integrate and analyze a quotation","Revise an outline for logical progression"] }
    ]
  },
  {
    id:"psychology", icon:"🧠", name:"Psychology", color:"green", description:"Explore behavior and mental processes through research, cognition, development, learning, and social influence.", level:"Intro / AP", topics:[
      { id:"research-methods", name:"Research Methods & Ethics", time:"26 min", difficulty:"Foundation", overview:"Psychological science uses systematic observation and statistical reasoning to test claims. Research design determines which conclusions are justified and how confidently they can be generalized.", points:["Operational definitions make variables measurable and replicable.","Correlation describes association but does not establish causation.","Random assignment supports causal inference; random sampling supports generalization.","Control groups and blinding reduce alternative explanations and expectancy effects.","Reliability concerns consistency, while validity concerns whether a measure captures its target.","Ethical research requires informed consent, risk protection, privacy, and debriefing."], detail:["Descriptive methods such as surveys, case studies, and naturalistic observation can reveal patterns but usually cannot isolate causes. Correlational studies quantify relationships, including direction and strength, while leaving third-variable and directionality problems unresolved.","Experiments manipulate an independent variable and measure a dependent variable. Random assignment balances participant differences across conditions, making the manipulated variable a more plausible cause of observed outcome differences.","Statistical significance does not automatically mean practical importance. Researchers also consider effect size, confidence intervals, replication, sampling quality, and whether the procedure represents the real-world behavior being discussed."], terms:[["Operational definition","A precise statement of how a variable is measured."],["Confounding variable","An uncontrolled factor that changes with the independent variable."],["Random assignment","Chance-based placement into experimental conditions."],["Validity","The extent to which a method measures what it claims."],["Debriefing","Post-study explanation of purpose and any necessary deception."]], check:["Identify independent and dependent variables","Separate correlation from causation","Explain random sampling versus random assignment","Evaluate a study for confounds, validity, and ethical concerns"] },
      { id:"learning-memory", name:"Learning & Memory", time:"30 min", difficulty:"Intermediate", overview:"Learning changes behavior or knowledge through experience, while memory encodes, stores, and retrieves information. Both are shaped by attention, context, reinforcement, and prior knowledge.", points:["Classical conditioning links stimuli; operant conditioning links behavior with consequences.","Reinforcement increases behavior, while punishment decreases it.","Working memory has limited capacity and actively manipulates information.","Elaborative encoding and organized retrieval cues improve long-term memory.","Spacing and retrieval practice outperform massed rereading.","Memory is reconstructive and vulnerable to interference and misinformation."], detail:["In classical conditioning, a previously neutral cue comes to predict a biologically meaningful event. In operant conditioning, consequences change the future probability of voluntary behavior. Positive and negative describe adding or removing a stimulus, not whether a consequence is good or bad.","Memory is often modeled as encoding, storage, and retrieval. Attention controls what enters working memory, while connections to existing knowledge make long-term encoding more durable. Retrieval depends partly on cues and context.","For studying, desirable difficulty matters. Spaced sessions and effortful recall may feel less fluent than rereading, but they produce stronger retention and reveal gaps early enough to correct them."], terms:[["Conditioned stimulus","A learned cue that predicts another stimulus."],["Reinforcement","A consequence that increases behavior."],["Working memory","Limited active processing of current information."],["Retrieval cue","A prompt that helps access stored information."],["Proactive interference","Older information disrupts newer learning."]], check:["Distinguish classical from operant conditioning","Classify positive and negative reinforcement examples","Explain encoding, storage, and retrieval","Design a spaced retrieval schedule for an exam"] },
      { id:"social-psychology", name:"Social Psychology", time:"28 min", difficulty:"Intermediate", overview:"Social psychology studies how people think about, influence, and relate to one another. Situations, groups, identities, and expectations can shape behavior in powerful but predictable ways.", points:["Attributions explain behavior through personal or situational causes.","The fundamental attribution error overweights disposition when judging others.","Conformity responds to group norms; obedience responds to authority.","Group polarization can intensify members' initial tendencies.","Prejudice involves attitudes, stereotypes involve beliefs, and discrimination involves behavior.","Cooperation and meaningful equal-status contact can reduce intergroup hostility."], detail:["People use quick social judgments because complete information is rarely available. These shortcuts can be useful, but they also produce predictable biases when context is ignored or expectations guide what evidence is noticed.","Classic conformity and obedience studies demonstrate situational power, but their findings should not be reduced to 'people always follow.' Behavior varies with unanimity, proximity, legitimacy, accountability, culture, and available alternatives.","Group processes can both improve and damage decisions. Diverse independent viewpoints may increase accuracy, while pressure for harmony, diffusion of responsibility, or identity threat can suppress careful evaluation."], terms:[["Attribution","An explanation for the cause of behavior."],["Conformity","Adjusting behavior or belief toward a group norm."],["Obedience","Compliance with a direct authority command."],["Group polarization","Strengthening of an initial group tendency after discussion."],["Bystander effect","Reduced helping when other observers are present."]], check:["Compare dispositional and situational attributions","Explain conditions that increase conformity","Distinguish stereotype, prejudice, and discrimination","Apply social-psychology concepts without ignoring context"] }
    ]
  }
];

export function SubjectLibrary({ pathname, onPath, onTool }) {
  const parts = pathname.split("/").filter(Boolean);
  const subject = subjects.find((item) => item.id === parts[1]);
  const topic = subject?.topics.find((item) => item.id === parts[2]);
  if (topic) return <TopicPage subject={subject} topic={topic} onPath={onPath} onTool={onTool}/>;
  if (subject) return <SubjectPage subject={subject} onPath={onPath}/>;
  return <Catalog onPath={onPath}/>;
}

function Catalog({ onPath }) {
  const guideCount = subjects.reduce((total,subject) => total + subject.topics.length,0);
  return <main className="subject-page"><section className="subject-hero"><span className="eyebrow">SHIBAAI SUBJECT LIBRARY</span><h1>Ready-made guides.<br/>Real understanding.</h1><p>Browse focused, student-friendly guides and turn any topic into active practice with one click.</p><div className="catalog-stats"><span><b>{subjects.length}</b> core subjects</span><span><b>{guideCount}</b> complete guides</span><span><b>100%</b> free preview</span></div></section><section className="subject-catalog"><div className="catalog-heading"><div><span className="eyebrow">CHOOSE A SUBJECT</span><h2>Where do you want to start?</h2></div><p>Every guide includes a detailed walkthrough, core concepts, vocabulary, mastery checks, and AI-powered practice.</p></div><div className="subject-grid">{subjects.map((subject) => <button className={`subject-card ${subject.color}`} key={subject.id} onClick={() => onPath(`/subjects/${subject.id}`)}><span className="subject-icon">{subject.icon}</span><div><small>{subject.level} · {subject.topics.length} guides</small><h2>{subject.name}</h2><p>{subject.description}</p><b>Explore {subject.name} →</b></div></button>)}</div><div className="coming-subjects"><span>COMING NEXT</span><div>⚛️ Physics　💻 Computer Science　🏛️ Government　📊 Statistics　🌎 Earth Science</div></div></section></main>;
}

function SubjectPage({ subject, onPath }) {
  return <main className="subject-page"><section className={`subject-detail-hero ${subject.color}`}><button onClick={() => onPath("/subjects")}>← All subjects</button><span>{subject.icon}</span><small>{subject.level}</small><h1>{subject.name}</h1><p>{subject.description}</p></section><section className="topic-section"><div className="catalog-heading"><div><span className="eyebrow">STUDY GUIDES</span><h2>Start with a core topic.</h2></div><p>Read the guide first, then use active practice to check what you remember.</p></div><div className="topic-grid">{subject.topics.map((topic,index) => <button key={topic.id} onClick={() => onPath(`/subjects/${subject.id}/${topic.id}`)}><span>{String(index+1).padStart(2,"0")}</span><div><small>{topic.difficulty} · {topic.time}</small><h3>{topic.name}</h3><p>{topic.overview}</p></div><b>→</b></button>)}</div></section></main>;
}

function TopicPage({ subject, topic, onPath, onTool }) {
  const walkthrough = topic.detail || [topic.overview,`Connect the main ideas: ${topic.points.join(" ")}`,`Use the vocabulary below to explain the topic in your own words, then complete each mastery check without referring back to the guide.`];
  return <main className="guide-page"><nav className="guide-breadcrumb"><button onClick={() => onPath("/subjects")}>Subjects</button><span>/</span><button onClick={() => onPath(`/subjects/${subject.id}`)}>{subject.name}</button><span>/</span><b>{topic.name}</b></nav><header className={`guide-header ${subject.color}`}><div><span className="eyebrow">{subject.name.toUpperCase()} STUDY GUIDE</span><h1>{topic.name}</h1><p>{topic.overview}</p><div className="guide-meta"><span>◷ {topic.time}</span><span>◈ {topic.difficulty}</span><span>✓ Detailed walkthrough</span><span>✓ Mastery checklist</span></div></div><span className="guide-mascot">{subject.icon}</span></header><div className="guide-layout"><article className="guide-content"><section><span className="section-number">01</span><div><h2>Detailed walkthrough</h2><div className="guide-prose">{walkthrough.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></section><section><span className="section-number">02</span><div><h2>Key concepts</h2><ul className="concept-list">{topic.points.map((point) => <li key={point}><span>✓</span>{point}</li>)}</ul></div></section><section><span className="section-number">03</span><div><h2>Essential vocabulary</h2><div className="vocab-list">{topic.terms.map(([term,definition]) => <div key={term}><strong>{term}</strong><p>{definition}</p></div>)}</div></div></section><section><span className="section-number">04</span><div><h2>Mastery check</h2><p className="check-intro">You’re ready when you can complete these without looking back:</p><div className="review-checks">{topic.check.map((item) => <label key={item}><input type="checkbox"/><span>{item}</span></label>)}</div></div></section></article><aside className="guide-sidebar"><div className="guide-action-card"><span>🐕</span><h3>Practice with Shiba</h3><p>Use this topic as a starting point for personalized study materials.</p><button className="button" onClick={() => onTool("quiz",topic)}>Generate a quiz</button><button onClick={() => onTool("flashcards",topic)}>Make flashcards</button></div><div className="guide-note"><strong>Remember</strong><p>AI-generated practice may make mistakes. Compare answers with this guide and your class materials.</p></div></aside></div></main>;
}

export { subjects };
